### ISSUE TITLE
Request for RAE2822 Airfoil Dataset

### ISSUE THREAD

**Issue by Gxinhu** [giovannicatalani/Aerodynamic-VAE#1]
Hi Catalani,

Thank you for your valuable work on this project! I found the paper titled “[A comparative study of learning techniques for the compressible aerodynamics over a transonic RAE2822 airfoil](https://www.sciencedirect.com/science/article/pii/S0045793022003516)” quite insightful.

Could you please guide me on where I might be able to find the RAE2822 airfoil dataset mentioned in the repository and paper? I would greatly appreciate your help!

Thank you once again for your contributions!

Best regards,  
Hu

**Comment by giovannicatalani** [comment]
Hello Gxinhu,
Yes I just updatted the readme of this repo. You will be able to find there the link to the zenodo archive to download the dataset.
If you have further questions do not hesitate to contact me. We just published a paper using a more advanced model and considering also this dataset. You can find it here [**Aero-Nef: Neural Fields for Rapid Aircraft Aerodynamic Simulations**](https://arxiv.org/abs/2407.19916).
